
import React from 'react';

export const CATEGORIES = ['ALG1', 'ALG2', 'ALG3', 'ORN1', 'ORN2', 'ORN3'];

export const TRANSLATIONS = {
  en: {
    appTitle: 'MK Clients',
    welcome: 'Welcome',
    logout: 'Logout',
    addNewClient: 'Add New Client',
    registeredClients: 'Registered Clients',
    clientDetails: 'Client Details',
    paymentDetails: 'Payment Details',
    lastName: 'Last Name',
    firstName: 'First Name',
    phoneNumber: 'Phone Number',
    dob: 'Date of Birth',
    passportNumber: 'Passport Number',
    issueDate: 'Issue Date',
    expiryDate: 'Expiry Date',
    placeOfIssue: 'Place of Issue',
    prevVisa: 'Previous Visa Number',
    visaFrom: 'Visa Valid From',
    visaTo: 'Visa Valid To',
    appointmentDate: 'Appointment Date',
    registrationDate: 'Registered On',
    dayStatus: 'Day / Status',
    category: 'Category',
    select: 'Select...',
    photo: 'Photo',
    register: 'Register Client',
    clear: 'Clear',
    paste: 'Paste',
    refresh: 'Refresh',
    search: 'Search by name, passport...',
    edit: 'Edit',
    copy: 'Copy',
    copyPayment: 'Copy Payment',
    delete: 'Delete',
    history: 'History',
    activityLog: 'Activity Log',
    action: 'Action',
    changes: 'Changes',
    noHistory: 'No activity recorded yet.',
    added: 'Added',
    modified: 'Modified',
    deleted: 'Deleted',
    from: 'From',
    to: 'To',
    cardNumber: 'Card Number',
    cardHolder: 'Card Holder Name',
    cvv: 'CVV',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    confirmDelete: 'Are you sure you want to delete this client?',
    actions: 'Actions',
    payment: 'Payment',
    id: 'ID',
    login: 'Login',
    signup: 'Sign Up',
    email: 'Email Address',
    password: 'Password',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    signInToAccount: 'Sign in to your account',
    createAccount: 'Create a new admin account',
    authDescription: '07 70 12 70 70',
    forgotPassword: 'Forgot password?',
    // New Admin and UI Strings
    activeAgentsNetwork: 'Active Agents Network',
    nodesSynchronized: 'Nodes Synchronized',
    forceSync: 'Force Sync',
    bulkSelect: 'Bulk Select',
    selectAll: 'Select All',
    deselectAll: 'Deselect All',
    globalPool: 'Global Pool',
    allRegisteredData: 'All Registered Data',
    secureEditEngine: 'Secure Edit Engine',
    fileAccessGranted: 'File Access Granted',
    deactivateTerminal: 'Deactivate Terminal',
    activateTerminal: 'Activate Terminal',
    aggregatedView: 'Aggregated View',
    nodesSelected: 'Nodes Selected',
    noRecordsFound: 'No Records Found',
    emptyPool: 'This data pool is currently empty. Switch agents or register new files.',
    filterNoMatch: 'The current filters (Date/Search) returned no matches.',
    clearFilters: 'Clear Active Filters',
    dataEntryNode: 'Data Entry Node Protocol',
    on: 'ON',
    off: 'OFF',
    rootAdmin: 'Root Administrator',
    portalVersion: 'Registration Portal v4.2',
    sessionLive: 'Session Live',
    wipeAgentDataConfirm: 'DANGER: Delete all records for agent "{email}"? This cannot be undone.',
    logistics: 'Logistics',
    protocol: 'Protocol',
    files: 'FILES',
    updated: 'Updated',
    uncategorizedHistory: 'Uncategorized History',
    today: 'Today',
    yesterday: 'Yesterday',
    registrationFailed: 'Registration failed',
    updateFailed: 'Update failed',
    checkEmail: 'Check your email for confirmation link!',
    days: {
      0: 'Sunday',
      1: 'Monday',
      2: 'Tuesday',
      3: 'Wednesday',
      4: 'Thursday',
      5: 'Friday',
      6: 'Saturday'
    },
    validation: {
      required: 'This field is required',
      passportLength: 'Passport must be exactly 9 digits',
      invalidCard: 'Invalid card number (Luhn check failed)',
      invalidExpiry: 'Invalid expiry date',
      cardExpired: 'Card has expired',
      cvvLength: 'CVV must be 3-4 digits',
      photoSize: 'Photo must be under 200KB',
      invalidEmail: 'Please enter a valid email address',
      passwordShort: 'Password must be at least 6 characters'
    }
  },
  fr: {
    appTitle: 'MK Clients',
    welcome: 'Bienvenue',
    logout: 'Déconnexion',
    addNewClient: 'Ajouter un Client',
    registeredClients: 'Clients Enregistrés',
    clientDetails: 'Détails du Client',
    paymentDetails: 'Détails du Paiement',
    lastName: 'Nom',
    firstName: 'Prénom',
    phoneNumber: 'Numéro de Téléphone',
    dob: 'Date de Naissance',
    passportNumber: 'Numéro de Passeport',
    issueDate: 'Date d\'Émission',
    expiryDate: 'Date d\'Expiration',
    placeOfIssue: 'Lieu d\'Émission',
    prevVisa: 'Numéro de Visa Précédent',
    visaFrom: 'Visa Valide Du',
    visaTo: 'Visa Valide Au',
    appointmentDate: 'Date de rendez-vous',
    registrationDate: 'Enregistré le',
    dayStatus: 'Jour / Statut',
    category: 'Catégorie',
    select: 'Sélectionner...',
    photo: 'Photo',
    register: 'Enregistrer le Client',
    clear: 'Effacer',
    paste: 'Coller',
    refresh: 'Actualiser',
    search: 'Rechercher par nom, passeport...',
    edit: 'Modifier',
    copy: 'Copier',
    copyPayment: 'Copier Paiement',
    delete: 'Supprimer',
    history: 'Historique',
    activityLog: 'Journal d\'activité',
    action: 'Action',
    changes: 'Changements',
    noHistory: 'Aucune activité enregistrée.',
    added: 'Ajouté',
    modified: 'Modifié',
    deleted: 'Supprimé',
    from: 'De',
    to: 'À',
    cardNumber: 'Numéro de Carte',
    cardHolder: 'Nom du Titulaire',
    cvv: 'CVV',
    saveChanges: 'Enregistrer',
    cancel: 'Annuler',
    confirmDelete: 'Êtes-vous sûr de vouloir supprimer ce client?',
    actions: 'Actions',
    payment: 'Paiement',
    id: 'ID',
    login: 'Connexion',
    signup: 'S\'inscrire',
    email: 'Adresse Email',
    password: 'Mot de passe',
    noAccount: "Vous n'avez pas de compte ?",
    hasAccount: 'Vous avez déjà un compte ?',
    signInToAccount: 'Connectez-vous à votre compte',
    createAccount: 'Créer un compte administrateur',
    authDescription: '07 70 12 70 70',
    forgotPassword: 'Mot de passe oublié ?',
    activeAgentsNetwork: 'Réseau des Agents Actifs',
    nodesSynchronized: 'Nœuds Synchronisés',
    forceSync: 'Forcer la Synchro',
    bulkSelect: 'Sélection Groupée',
    selectAll: 'Tout Sélectionner',
    deselectAll: 'Tout Désélectionner',
    globalPool: 'Pool Global',
    allRegisteredData: 'Toutes les données enregistrées',
    secureEditEngine: 'Moteur d\'édition sécurisé',
    fileAccessGranted: 'Accès au fichier accordé',
    deactivateTerminal: 'Désactiver le terminal',
    activateTerminal: 'Activer le terminal',
    aggregatedView: 'Vue agrégée',
    nodesSelected: 'Nœuds sélectionnés',
    noRecordsFound: 'Aucun enregistrement trouvé',
    emptyPool: 'Ce pool de données est actuellement vide. Changez d\'agent ou enregistrez de nouveaux fichiers.',
    filterNoMatch: 'Les filtres actuels (Date/Recherche) n\'ont donné aucun résultat.',
    clearFilters: 'Effacer les filtres actifs',
    dataEntryNode: 'Protocole de nœud de saisie',
    on: 'ACTIVÉ',
    off: 'DÉSACTIVÉ',
    rootAdmin: 'Administrateur Racine',
    portalVersion: 'Portail d\'enregistrement v4.2',
    sessionLive: 'Session Active',
    wipeAgentDataConfirm: 'DANGER : Supprimer tous les enregistrements de l\'agent "{email}" ? Cette action est irréversible.',
    logistics: 'Logistique',
    protocol: 'Protocole',
    files: 'DOSSIERS',
    updated: 'Mis à jour',
    uncategorizedHistory: 'Historique non catégorisé',
    today: 'Aujourd\'hui',
    yesterday: 'Hier',
    registrationFailed: 'Échec de l\'enregistrement',
    updateFailed: 'Échec de la mise à jour',
    checkEmail: 'Vérifiez vos e-mails pour le lien de confirmation !',
    days: {
      0: 'Dimanche',
      1: 'Lundi',
      2: 'Mardi',
      3: 'Mercredi',
      4: 'Jeudi',
      5: 'Vendredi',
      6: 'Samedi'
    },
    validation: {
      required: 'Ce champ est obligatoire',
      passportLength: 'Le passeport doit comporter exactement 9 chiffres',
      invalidCard: 'Numéro de carte invalide',
      invalidExpiry: 'Date d\'expiration invalide',
      cardExpired: 'La carte est expirée',
      cvvLength: 'Le CVV doit comporter 3-4 chiffres',
      photoSize: 'La photo doit faire moins de 200Ko',
      invalidEmail: 'Veuillez entrer une adresse email valide',
      passwordShort: 'Le mot de passe doit faire au moins 6 caractères'
    }
  },
  ar: {
    appTitle: 'MK Clients',
    welcome: 'مرحباً',
    logout: 'تسجيل الخروج',
    addNewClient: 'إضافة عميل جديد',
    registeredClients: 'العملاء المسجلون',
    clientDetails: 'بيانات العميل',
    paymentDetails: 'بيانات الدفع',
    lastName: 'اللقب',
    firstName: 'الاسم الأول',
    phoneNumber: 'رقم الهاتف',
    dob: 'تاريخ الميلاد',
    passportNumber: 'رقم جواز السفر',
    issueDate: 'تاريخ الإصدار',
    expiryDate: 'تاريخ الانتهاء',
    placeOfIssue: 'مكان الإصدار',
    prevVisa: 'رقم التأشيرة السابقة',
    visaFrom: 'تأشيرة صالحة من',
    visaTo: 'تأشيرة صالحة إلى',
    appointmentDate: 'تاريخ الموعد',
    registrationDate: 'تاريخ التسجيل',
    dayStatus: 'اليوم / الحالة',
    category: 'الفئة',
    select: 'اختر...',
    photo: 'الصورة',
    register: 'تسجيل العميل',
    clear: 'مسح',
    paste: 'لصق',
    refresh: 'تحديث',
    search: 'بحث بالاسم، الجواز...',
    edit: 'تعديل',
    copy: 'نسخ',
    copyPayment: 'نسخ بيانات الدفع',
    delete: 'حذف',
    history: 'السجل',
    activityLog: 'سجل العمليات',
    action: 'العملية',
    changes: 'التغييرات',
    noHistory: 'لا يوجد سجل عمليات بعد.',
    added: 'تمت الإضافة',
    modified: 'تم التعديل',
    deleted: 'تم الحذف',
    from: 'من',
    to: 'إلى',
    cardNumber: 'رقم البطاقة',
    cardHolder: 'اسم حامل البطاقة',
    cvv: 'رمز الأمان',
    saveChanges: 'حفظ التغييرات',
    cancel: 'إلغاء',
    confirmDelete: 'هل أنت متأكد من حذف هذا العميل؟',
    actions: 'الإجراءات',
    payment: 'الدفع',
    id: 'رقم',
    login: 'تسجيل الدخول',
    signup: 'إنشاء حساب',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    noAccount: 'ليس لديك حساب؟',
    hasAccount: 'لديك حساب بالفعل؟',
    signInToAccount: 'تسجيل الدخول إلى حسابك',
    createAccount: 'إنشاء حساب مسؤول جديد',
    authDescription: '07 70 12 70 70',
    forgotPassword: 'نسيت كلمة المرور؟',
    activeAgentsNetwork: 'شبكة الوكلاء النشطين',
    nodesSynchronized: 'عقد متزامنة',
    forceSync: 'فرض المزامنة',
    bulkSelect: 'تحديد متعدد',
    selectAll: 'تحديد الكل',
    deselectAll: 'إلغاء تحديد الكل',
    globalPool: 'المجمع العالمي',
    allRegisteredData: 'جميع البيانات المسجلة',
    secureEditEngine: 'محرك تعديل آمن',
    fileAccessGranted: 'تم منح الوصول للملف',
    deactivateTerminal: 'إيقاف تشغيل المحطة',
    activateTerminal: 'تنشيط المحطة',
    aggregatedView: 'عرض مجمع',
    nodesSelected: 'عقد مختارة',
    noRecordsFound: 'لم يتم العثور على سجلات',
    emptyPool: 'هذا المجمع فارغ حالياً. قم بتغيير الوكلاء أو تسجيل ملفات جديدة.',
    filterNoMatch: 'الفلاتر الحالية (التاريخ/البحث) لم ترجع أي نتائج.',
    clearFilters: 'مسح الفلاتر النشطة',
    dataEntryNode: 'بروتوكول عقدة إدخال البيانات',
    on: 'مفعل',
    off: 'معطل',
    rootAdmin: 'مسؤول النظام',
    portalVersion: 'بوابة التسجيل v4.2',
    sessionLive: 'جلسة نشطة',
    wipeAgentDataConfirm: 'خطر: حذف جميع سجلات الوكيل "{email}"؟ لا يمكن التراجع عن هذه العملية.',
    logistics: 'الخدمات اللوجستية',
    protocol: 'البروتوكول',
    files: 'ملفات',
    updated: 'محدث',
    uncategorizedHistory: 'تاريخ غير مصنف',
    today: 'اليوم',
    yesterday: 'أمس',
    registrationFailed: 'فشل التسجيل',
    updateFailed: 'فشل التحديث',
    checkEmail: 'تحقق من بريدك الإلكتروني للحصول على رابط التأكيد!',
    days: {
      0: 'الأحد',
      1: 'الاثنين',
      2: 'الثلاثاء',
      3: 'الأربعاء',
      4: 'الخميس',
      5: 'الجمعة',
      6: 'السبت'
    },
    validation: {
      required: 'هذا الحقل مطلوب',
      passportLength: 'يجب أن يتكون الجواز من 9 أرقام بالضبط',
      invalidCard: 'رقم البطاقة غير صالح',
      invalidExpiry: 'تاريخ انتهاء غير صالح',
      cardExpired: 'البطاقة منتهية الصلاحية',
      cvvLength: 'يجب أن يكون الرمز 3-4 أرقام',
      photoSize: 'هذا الملف كبير جداً (200 كيلوبايت كحد أقصى)',
      invalidEmail: 'يرجى إدخال بريد إلكتروني صالح',
      passwordShort: 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل'
    }
  }
};
