
import React from 'react';

export const CATEGORIES = ['ALG1', 'ALG2', 'ALG3', 'ORN1', 'ORN2', 'ORN3'];

export const TRANSLATIONS = {
  en: {
    appTitle: 'MK Clients',
    welcome: 'Welcome',
    logout: 'Logout',
    addNewClient: 'Add New Client',
    registeredClients: 'Registered Clients',
    clientDetails: 'Client Details',
    paymentDetails: 'Payment Details',
    lastName: 'Last Name',
    firstName: 'First Name',
    phoneNumber: 'Phone Number',
    dob: 'Date of Birth',
    passportNumber: 'Passport Number',
    issueDate: 'Issue Date',
    expiryDate: 'Expiry Date',
    placeOfIssue: 'Place of Issue',
    prevVisa: 'Previous Visa Number',
    visaFrom: 'Visa Valid From',
    visaTo: 'Visa Valid To',
    appointmentDate: 'Appointment Date',
    registrationDate: 'Registered On',
    dayStatus: 'Day / Status',
    category: 'Category',
    select: 'Select...',
    photo: 'Photo',
    register: 'Register Client',
    clear: 'Clear',
    paste: 'Paste',
    refresh: 'Refresh',
    search: 'Search by name, passport...',
    edit: 'Edit',
    copy: 'Copy',
    copyPayment: 'Copy Payment',
    delete: 'Delete',
    history: 'History',
    activityLog: 'Activity Log',
    action: 'Action',
    changes: 'Changes',
    noHistory: 'No activity recorded yet.',
    added: 'Added',
    modified: 'Modified',
    deleted: 'Deleted',
    from: 'From',
    to: 'To',
    cardNumber: 'Card Number',
    cardHolder: 'Card Holder Name',
    cvv: 'CVV',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    confirmDelete: 'Are you sure you want to delete this client?',
    actions: 'Actions',
    payment: 'Payment',
    id: 'ID',
    login: 'Login',
    signup: 'Sign Up',
    email: 'Email Address',
    password: 'Password',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    signInToAccount: 'Sign in to your account',
    createAccount: 'Create a new admin account',
    authDescription: '07 70 12 70 70',
    days: {
      0: 'Sunday',
      1: 'Monday',
      2: 'Tuesday',
      3: 'Wednesday',
      4: 'Thursday',
      5: 'Friday',
      6: 'Saturday'
    },
    validation: {
      required: 'This field is required',
      passportLength: 'Passport must be exactly 9 digits',
      invalidCard: 'Invalid card number (Luhn check failed)',
      invalidExpiry: 'Invalid expiry date',
      cardExpired: 'Card has expired',
      cvvLength: 'CVV must be 3-4 digits',
      photoSize: 'Photo must be under 200KB',
      invalidEmail: 'Please enter a valid email address',
      passwordShort: 'Password must be at least 6 characters'
    }
  },
  fr: {
    appTitle: 'MK Clients',
    welcome: 'Bienvenue',
    logout: 'Déconnexion',
    addNewClient: 'Ajouter un Nouveau Client',
    registeredClients: 'Clients Enregistrés',
    clientDetails: 'Détails du Client',
    paymentDetails: 'Détails du Paiement',
    lastName: 'Nom',
    firstName: 'Prénom',
    phoneNumber: 'Numéro de Téléphone',
    dob: 'Date de Naissance',
    passportNumber: 'Numéro de Passeport',
    issueDate: 'Date d\'Émission',
    expiryDate: 'Date d\'Expiration',
    placeOfIssue: 'Lieu d\'Émission',
    prevVisa: 'Numéro de Visa Précédent',
    visaFrom: 'Visa Valide Du',
    visaTo: 'Visa Valide Au',
    appointmentDate: 'Date de rendez-vous',
    registrationDate: 'Enregistré le',
    dayStatus: 'Jour / Statut',
    category: 'Catégorie',
    select: 'Sélectionner...',
    photo: 'Photo',
    register: 'Enregistrer le Client',
    clear: 'Effacer',
    paste: 'Coller',
    refresh: 'Actualiser',
    search: 'Rechercher par nom, passeport...',
    edit: 'Modifier',
    copy: 'Copier',
    copyPayment: 'Copier Paiement',
    delete: 'Supprimer',
    history: 'Historique',
    activityLog: 'Journal d\'activité',
    action: 'Action',
    changes: 'Changements',
    noHistory: 'Aucune activité enregistrée.',
    added: 'Ajouté',
    modified: 'Modifié',
    deleted: 'Supprimé',
    from: 'De',
    to: 'À',
    cardNumber: 'Numéro de Carte',
    cardHolder: 'Nom du Titulaire',
    cvv: 'CVV',
    saveChanges: 'Enregistrer',
    cancel: 'Annuler',
    confirmDelete: 'Êtes-vous sûr de vouloir supprimer ce client?',
    actions: 'Actions',
    payment: 'Paiement',
    id: 'ID',
    login: 'Connexion',
    signup: 'S\'inscrire',
    email: 'Adresse Email',
    password: 'Mot de passe',
    noAccount: "Vous n'avez pas de compte ?",
    hasAccount: 'Vous avez déjà un compte ?',
    signInToAccount: 'Connectez-vous à votre compte',
    createAccount: 'Créer un nouveau compte administrateur',
    authDescription: '07 70 12 70 70',
    days: {
      0: 'Dimanche',
      1: 'Lundi',
      2: 'Mardi',
      3: 'Mercredi',
      4: 'Jeudi',
      5: 'Vendredi',
      6: 'Samedi'
    },
    validation: {
      required: 'Ce champ est obligatoire',
      passportLength: 'Le passeport doit comporter exactement 9 chiffres',
      invalidCard: 'Numéro de carte invalide',
      invalidExpiry: 'Date d\'expiration invalide',
      cardExpired: 'La carte est expirée',
      cvvLength: 'Le CVV doit comporter 3-4 chiffres',
      photoSize: 'La photo doit faire moins de 200Ko',
      invalidEmail: 'Veuillez entrer une adresse email valide',
      passwordShort: 'Le mot de passe doit faire au moins 6 caractères'
    }
  },
  ar: {
    appTitle: 'MK Clients',
    welcome: 'مرحباً',
    logout: 'تسجيل الخروج',
    addNewClient: 'إضافة عميل جديد',
    registeredClients: 'العملاء المسجلون',
    clientDetails: 'بيانات العميل',
    paymentDetails: 'بيانات الدفع',
    lastName: 'اللقب',
    firstName: 'الاسم الأول',
    phoneNumber: 'رقم الهاتف',
    dob: 'تاريخ الميلاد',
    passportNumber: 'رقم جواز السفر',
    issueDate: 'تاريخ الإصدار',
    expiryDate: 'تاريخ الانتهاء',
    placeOfIssue: 'مكان الإصدار',
    prevVisa: 'رقم التأشيرة السابقة',
    visaFrom: 'تأشيرة صالحة من',
    visaTo: 'تأشيرة صالحة إلى',
    appointmentDate: 'تاريخ الموعد',
    registrationDate: 'تاريخ التسجيل',
    dayStatus: 'اليوم / الحالة',
    category: 'الفئة',
    select: 'اختر...',
    photo: 'الصورة',
    register: 'تسجيل العميل',
    clear: 'مسح',
    paste: 'لصق',
    refresh: 'تحديث',
    search: 'بحث بالاسم، الجواز...',
    edit: 'تعديل',
    copy: 'نسخ',
    copyPayment: 'نسخ بيانات الدفع',
    delete: 'حذف',
    history: 'السجل',
    activityLog: 'سجل العمليات',
    action: 'العملية',
    changes: 'التغييرات',
    noHistory: 'لا يوجد سجل عمليات بعد.',
    added: 'تمت الإضافة',
    modified: 'تم التعديل',
    deleted: 'تم الحذف',
    from: 'من',
    to: 'إلى',
    cardNumber: 'رقم البطاقة',
    cardHolder: 'اسم حامل البطاقة',
    cvv: 'رمز الأمان',
    saveChanges: 'حفظ التغييرات',
    cancel: 'إلغاء',
    confirmDelete: 'هل أنت متأكد من حذف هذا العميل؟',
    actions: 'الإجراءات',
    payment: 'الدفع',
    id: 'رقم',
    login: 'تسجيل الدخول',
    signup: 'إنشاء حساب',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    noAccount: 'ليس لديك حساب؟',
    hasAccount: 'لديك حساب بالفعل؟',
    signInToAccount: 'تسجيل الدخول إلى حسابك',
    createAccount: 'إنشاء حساب مسؤول جديد',
    authDescription: '07 70 12 70 70',
    days: {
      0: 'الأحد',
      1: 'الاثنين',
      2: 'الثلاثاء',
      3: 'الأربعاء',
      4: 'الخميس',
      5: 'الجمعة',
      6: 'السبت'
    },
    validation: {
      required: 'هذا الحقل مطلوب',
      passportLength: 'يجب أن يتكون الجواز من 9 أرقام بالضبط',
      invalidCard: 'رقم البطاقة غير صالح',
      invalidExpiry: 'تاريخ انتهاء غير صالح',
      cardExpired: 'البطاقة منتهية الصلاحية',
      cvvLength: 'يجب أن يكون الرمز 3-4 أرقام',
      photoSize: 'هذا الملف كبير جداً (200 كيلوبايت كحد أقصى)',
      invalidEmail: 'يرجى إدخال بريد إلكتروني صالح',
      passwordShort: 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل'
    }
  }
};
